name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install or update dependencies
      - name: Setup Node.js and install/update dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Check for changes in package-lock.json
        run: |
          git fetch --prune --unshallow
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep package-lock.json || echo "::set-output name=changed::true"
      - name: Install or update dependencies
        if: steps.setup-node.outputs.changed == 'true'
        run: npm ci

      # Install or update Cypress and other tools
      - name: Install or update Cypress and other tools
        if: steps.setup-node.outputs.changed == 'true'
        run: npm install --no-save cypress mochawesome mochawesome-merge mochawesome-report-generator

      # Run Cypress tests
      - name: Run Cypress tests
        if: steps.setup-node.outputs.changed == 'true'
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: 'http://localhost:3000'  # Assuming your application runs on localhost:3000
