name: Cypress Tests

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cypress:run  # Adjust this command based on your npm scripts

    # Add steps to deploy to AWS if needed
