name: Run Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Trigger manually if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force

      # Install cypress-mochawesome-reporter if not already installed
      - name: Install cypress-mochawesome-reporter
        run: |
          if ! npm ls cypress-mochawesome-reporter; then
            npm install --save-dev cypress-mochawesome-reporter
          fi

      # Setup Node.js and install dependencies if version has changed
      - name: Setup Node.js and install dependencies
        if: needs.setup.outputs.versionChanged == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies if version has changed
      - name: Install dependencies
        if: needs.setup.outputs.versionChanged == 'true'
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run --if-present
