name: Run Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Trigger manually if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force

      # Install cypress-mochawesome-reporter if not already installed
      - name: Install cypress-mochawesome-reporter
        run: |
          if ! npm ls cypress-mochawesome-reporter; then
            npm install --save-dev cypress-mochawesome-reporter
          fi

      # Setup Node.js and install dependencies if version has changed
      - name: Setup Node.js and install dependencies
        if: needs.setup.outputs.versionChanged == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies if version has changed
      - name: Install dependencies
        if: needs.setup.outputs.versionChanged == 'true'
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run --if-present

           # Wait for HTML report to appear (sleep for 20 seconds)
      - name: Wait for HTML report
        run: |
          timeout=30  # Timeout in seconds
          while [ ! -f mochawesome-report/index.html ]; do
            sleep 1
            ((timeout--))
            if [ $timeout -eq 0 ]; then
              echo "Timeout reached, HTML report not found."
              exit 1
            fi
          done



      # Upload Mochawesome report as an artifact
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report
