name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

      # Setup Node.js and install/update dependencies
      - name: Setup Node.js and install/update dependencies
        uses: actions/setup-node@v4  # Updated to v4 for Node.js 20 support
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Mocha tests and generate reports
      - name: Run Mocha tests
        run: npm test

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run --if-present

      # Upload Mocha report
      - name: Upload Mocha report
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: mocha-report
          path: mochawesome-report

      # Generate and upload merged Cypress and Mocha reports
      - name: Generate merged report
        run: |
          npx mochawesome-merge mochawesome-report/*.json > mochawesome-report/merged-report.json
          npx marge mochawesome-report/merged-report.json -o mochawesome-report

      - name: Upload merged report
        if: always()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: merged-report
          path: mochawesome-report
