name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

      # Setup Node.js and install dependencies
      - name: Setup Node.js and install dependencies
        uses: actions/setup-node@v4  # Updated to v4 for Node.js 20 support
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run --if-present
